### PR TITLE
feat: added button icons to CP

### PR DESCRIPTION
**Pull request by abhijeetekad**

### CODE REVIEW

**Comment by abhijeetekad** [comment]
preview link: https://deploy-preview-8--focused-shaw-005f2f.netlify.app/documentation2/documentation2#button

**Comment by t007rushi** [comment]
I think just do some modification for text overlay if its product card have text bottom with less font-size or else make separate img+text only card for good Look & feel

**Comment by KanekarSnehal** [comment]
The icon button code doesn't have that green border around it, please check and make the changes.

**Comment by abhijeetekad** [comment]
> The icon button code doesn't have that green border around it, please check and make the changes.

ok

**Comment by abhijeetekad** [comment]
> I think just do some modification for text overlay if its product card have text bottom with less font-size or else make separate img+text only card for good Look & feel

ok.. I have done some changes their and will keep that in mind for next time..

**Comment by abhijeetekad** [comment]
> I think just do some modification for text overlay if its product card have text bottom with less font-size or else make separate img+text only card for good Look & feel

ok.. I have done some changes there and will keep that in mind for next time..

**Pull request merged**
